### ISSUE TITLE
get_gpo_computer was removed from Empire

### ISSUE THREAD

**Issue by DanMcInerney** [byt3bl33d3r/DeathStar#54]
I know you're already aware of this. Figured I'd document it cuz we might be able to fix it soon. I'll see about implementing that one liner from harmj0y on the Empire issue tomorrow.

**Comment by DanMcInerney** [comment]
for documentation: 

Get-DomainOU -GPLink [GUID] | % { Get-DomainComputer -SearchBase $_.distinguishedname }

**Comment by byt3bl33d3r** [comment]
Submitted https://github.com/EmpireProject/Empire/pull/995. Basically a re-implementation of the old module using that one liner.

Hopefully it will be merged soon cause this broke the GPP password privesc in DeathStar

**Comment by rfrogman** [comment]
Any workarounds for this? I do not see were Empire has addresses the issue yet.

**Comment by byt3bl33d3r** [comment]
@rfrogman Development on this project is at a stand still because of all the breaking changes Empire has made to it's API and modules over the past year and I don't have time to keep fixing them.

The goal is going to be to re-write this to use the [SILENTTRINITY](https://github.com/byt3bl33d3r/SILENTTRINITY), that way I have control over both projects, however that will take time as to do that I'm going to need to write a Rest-API and all of the necessary modules.

**Comment by d0nu75** [comment]
Hey @byt3bl33d3r, any update on implementing this with SILENTTRINITY?
